language: node_js
node_js:
- '6'
before_install:
# TODO OSS
# - npm i npm-cli-login -g
# - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
# - npm who
- echo "registry = https://realglobe.artifactoryonline.com/realglobe/api/npm/npm-virtual" > $HOME/.npmrc
- curl -u${NPM_USER}:${NPM_PASSWORD} "https://realglobe.artifactoryonline.com/realglobe/api/npm/auth" >> $HOME/.npmrc
- cat $HOME/.npmrc
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- ./ci/doc.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "MuYb5NJD32mmzVFVvwKItpGjZkV2ue91NVfRJ64IAnbcK6hEU4uR0BkplQT97Tx3zZCtqKBvOVhMdL7/RZ9nK+cpI/Y2lxMtuvb5Z3DYH8CGCnwsFITQJNAn0BPcmr8ZYy2yBBzuWIJufDcdyxEeOfDTi3S+PBm82MSwcfQVjEJQDcNy7uas/n/hcgMsV1YwG3fSXzTVetgHE8B7SRusjNvvL3wZeez+/iJ6QHyb2PitGcm1P35PaEzhxK/97diH/lAJQtfTwcm/aCJwkmG3JCjKHZMGeDwo5Crp01sjkzQTYHcpO1VlXtc8oXJRmRLMzj1L9ZQy+OWfmkbpAqOnqx6tFkoUiu6wB4iIV+HuVcCkFYmo9yy4Qo9l7wUMgIVF+UaA4w/lyqC8PJTYqOk0LWGfB/A2SQJmdrT1BYMQLMI066qya9zvMKnuUSkcLF0pg2sch7i4az4Vzpl9zoKY072Lw9eIKm8OwsqJ/TNGUeEmdLNU7F/GCX1/Ow7ZdW8LYGLkVBU8lVZmOBpR5t6BRoExTRhNtteJYyvZgqQtQSoHjYVR7LqpOYT7Bo3WYlBtOV325kuRk1laY0vSv/S+rnbwIuLtA9G/pOWij4sCaSfHJpM1rJrwYlrRaKVQ944HOZ4UqMOjhGZib2ZJKGeafoyKBzx5nWUxbGXuuDjmU+U="
