language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "mzdb2eAXQg6ccXpeBAzgQ0Lga67Eri9FvlM4lIQAdQ9RSwOTsKCN8pqlpL/YBKnB7ainqcViUM0VbG3nztgohmvh22/VVJYkTK5ug8ZpAMOIibbAH7SDVPWIOmo207TMeJy1fO8tv8BBQItfTGw/9Wx4mM0jtje2mlL2Uob9hntV8vY3jpFMyMgPq5ZMD9C03wYjzfkC8XB1DqeYyiqmL7+2uLsRucZx5jv3ZOSttDLjIYffJGIOAyq9+0Odgnwwkw6weJVD+nTRnUbehlxucJBaLyjcYbPxn4gT8h/pVO1nNgaQJLlqSeSKw6sI8aMBQvtb6z2jfeG+ClPgb1GLBJXMJcFASunN/ofW+xYh8NjjiOE6+yHKfwfcrhVDdmMMfnWzt77TaqRil9qf8n2TX6HX/r8Sz3WNUhADVrQ77RTl2sQasv3MjduPSrq8qVJtkjesHNyH8s/rcTVXmfsh6oYK0eQ6u2w1yYEgDb++yLldmjN0Kho29q86FMnFDn6tvgMh4ujwKGmohZDRDvEFaDDLtpfuODIKM67mkj8/bSa7M7eHw1dg54Xd5A8d7hUQfKQnXAHv1h7OgPp15IwaLsOlhSCeQnoZE73oSF6ClsGhSaGYzbLPb+1lbG7yKkqE+uPxC0mVjt36pzVslK+txQrtgRSaloqF9uaTFbV92MM="
